version: '3.7'

services:
  proxy:
    image: nginx:1.25.1
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.4.0
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  validation:
    entrypoint: ["echo", "Service disabled"] # Note: this probably go in the future
    restart: "no"
  dbcleanup:
    restart: "no"
  filehost:
    restart: "no"
  sink:
    restart: "no"
  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  update-bestuurseenheid-mock-login:
    restart: "no"
  reasoner:
    restart: "no"
  op-public-consumer:
    restart: "no"