version: "3.7"

services:
  lpdc:
    restart: "no"
  proxy:
    image: nginx:1.25.1
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.4.0
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  dbcleanup:
    restart: "no"
  sink:
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"

  ################################################################################
  # LPDC
  ################################################################################

  lpdc-management:
    restart: "no"

  lpdc-publish:
    restart: "no"

  lpdc-ldes-consumer:
    restart: "no"

  ################################################################################
  # DELTA GENERAL
  ################################################################################

  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  