version: "3.7"

services:
  mocklogin:
    image: lblod/mock-login-service:0.4.0

  dashboard:
    environment:
      VIRTUAL_HOST: "acc.dashboard.lpdc.lpdc-dev.s.redhost.be"
      LETSENCRYPT_HOST: "acc.dashboard.lpdc.lpdc-dev.s.redhost.be"
      LETSENCRYPT_EMAIL: "info@redpencil.io"
    #############################
    # Basic auth config.
    #############################
    volumes:
      - ./config/basic-auth:/etc/nginx/conf.d
    networks:
      - proxy
      - default

  lpdc:
    environment:
      VIRTUAL_HOST: "acc.lpdc-dev.s.redhost.be,acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_HOST: "acc.lpdc-dev.s.redhost.be,acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_EMAIL: "info@redpencil.io"
      EMBER_LOKET_URL: "https://loket.lblod.info/"
      EMBER_ACMIDM_CLIENT_ID: "<ACMIDM_CLIENT_ID>"
      EMBER_ACMIDM_AUTH_URL: "https://authenticatie.vlaanderen.be/op/v1/auth"
      EMBER_ACMIDM_LOGOUT_URL: "https://authenticatie.vlaanderen.be/op/v1/logout"
      EMBER_ACMIDM_AUTH_REDIRECT_URL: "https://acc.lpdc.lokaalbestuur.lblod.info/authorization/callback"
      EMBER_ACMIDM_SWITCH_REDIRECT_URL: "https://acc.lpdc.lokaalbestuur.lblod.info/switch-login"
    #############################
    # Basic auth config.
    #############################
    volumes:
      - ./config/basic-auth:/etc/nginx/conf.d
    networks:
      - proxy
      - default

  login:
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "<ACMIDM_CLIENT_ID>"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://acc.lpdc.lokaalbestuur.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "<ACMIDM_AUTH_CLIENT_SECRET>"

  lpdc-publish:
    entrypoint: ["echo", "Service-disabled since production data cannot be connected to test ipdc environment"]
    restart: "no"

  lpdc-ldes-consumer:
    entrypoint: ["echo", "Service-disabled since production data cannot be connected to test ipdc environment"]
    restart: "no"

networks:
  proxy:
    external:
      name: letsencrypt_default