steps:
  run-latest-test-and-deploy-to-dev:
    image: ubuntu:22.04
    commands:
      - echo "install ssh"
      - apt-get update
      - apt-get install -y openssh-client
      - mkdir ~/.ssh
      - ssh-keyscan -p 22 lpdc-dev.s.redhost.be >> ~/.ssh/known_hosts
      - cat ~/.ssh/known_hosts
      - echo "$${SSH_KEY}" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "Building from branch = ${CI_COMMIT_BRANCH}"
      - ssh root@lpdc-dev.s.redhost.be 'cd /data/app-lpdc-digitaal-loket-ci && git fetch && git checkout ${CI_COMMIT_BRANCH} && git pull && cd /data/app-lpdc-digitaal-loket-ci/tests && npx playwright install && ./run-latest.sh'
      - ssh root@lpdc-dev.s.redhost.be 'cd /data/app-lpdc-digitaal-loket-dev && git fetch && git pull && docker compose down && docker compose pull && docker compose up -d'

    secrets: [ ssh_key ]

when:
  branch: kunlabora
  event: push